using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

namespace Spoorbaan
{
    public class Lamp
    {
        //LampKleur kan eigenlijk alleen Rood of Groen zijn bij een spoorlicht, slecht af te handelen in string.
        //Alle lampen zullen de dezelfde straal hebben, dus contant werkt beter hiervoor
        protected LampKleur kleur;
        protected const int STRAAL = 2;
        protected int x;
        protected int y;
        protected LampStatus status;
        Graphics g;

        //Default Lamp heeft altijd een x en y coordinaat nodig, maar de straal kleur en status kunnen default zijn
        public Lamp(int x, int y)
        {
            this.x = x;
            this.y = y;
            kleur = LampKleur.Rood;
            status = LampStatus.Uit;

        }
        //simpele autogenerated get/set, deze zal vaak voorkomen
        public LampKleur Kleur
        {
            get => kleur;
            set
            {
                kleur = value;
            }
        }

        public LampStatus Status
        {
            get => status;
            set
            {
                status = value;
            }
        }
        //Idee is dat er eerst wordt gekeken of de lamp aanstaand voordat de kleur van de lamp wordt gecheckt. Bij het eind van een pad tekenen.
        //Kleur Default situatie zou niet moeten voorkomen omdat kleur gevult wordt in constructor, maar in het geval dat het wel voorkomt is er een opvang.
        public void Teken()
        {
            SolidBrush sb = new SolidBrush(Color.Black);
            if (status == LampStatus.Aan)
            {
                switch (kleur)
                {
                    case LampKleur.Groen:
                        sb.Color = Color.Green;
                        g.FillEllipse(sb, x, y, STRAAL, STRAAL);
                        break;
                    case LampKleur.Rood:
                        sb.Color = Color.Red;
                        g.FillEllipse(sb, x, y, STRAAL, STRAAL);
                        break;
                    default:
                        sb.Color = Color.Gold;
                        g.FillEllipse(sb, x, y, STRAAL, STRAAL);
                        break;
                }
            }
            else
            {
                g.FillEllipse(sb, x, y, 5, 5);
            }
        }
    }
}